services:
  translate:
    container_name: translate
    image: mcim_translate
    build:
      context: .
      dockerfile: ./translate-mod-summary/Dockerfile
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./config.json:/config.json
    deploy:
      resources:
         limits:
            memory: 200M